### ISSUE TITLE
Issue while running ionic serve

### ISSUE THREAD

**Issue by Gitesh502** [bkorobeinikov/movieapp-ionic#2]
Hi, I am new to ionic ,

After some point got below error while doing ionic serve

[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...

**Comment by shruthiMallappa** [comment]
Hi all, 
how to resolve the issue of getting error while running ionic serve in ionic2
Getting the error as


Error: Cannot find module '@ionic/discover'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/devapp.js:4:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


please help me resolve the problem,
Thank you.

**Comment by MaBbKhawaja** [comment]
its showing try again later

**Comment by Jaffar29sha** [comment]
$ npm install
npm WARN deprecated @types/x2js@3.1.0: This is a stub types definition for x2js (https://code.google.com/p/x2js/). x2js provides its own type definitions, so you don't need @types/x2js installed!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

> node-sass@4.5.0 install E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:13:12)\n    at F (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:68:19)\n    at E (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:80:29)\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:89:16\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\isexe\\index.js:42:5\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:13:12)\n    at F (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:68:19)\n    at E (E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:80:29)\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\which\\which.js:89:16\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\isexe\\index.js:42:5\n    at E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\MY WorkspacE\\IONIC_\\movieapp-ionic\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\MY WorkspacE\IONIC_\movieapp-ionic\node_modules\node-sass
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ionic-angular@3.1.1 requires a peer of @angular/common@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/compiler@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/compiler-cli@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/core@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/forms@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/http@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/platform-browser@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of @angular/platform-browser-dynamic@4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ionic-angular@3.1.1 requires a peer of rxjs@5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN movieapp@1.1.0 No repository field.
npm WARN movieapp@1.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wessc5\AppData\Roaming\npm-cache\_logs\2018-12-14T16_19_26_368Z-debug.log
